import style from './Contributions.module.css';
import ContributionItem from './../ContributionItem/ContributionItem';

export default function Contributions() {
  
  return (
    <div className={style.container}>
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
{/*       <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem />
      <ContributionItem /> */}
    </div>
  );
}

